server:
  port: 8000
database:
  postgres:
    host: localhost
    port: 5000
    user: postgres
    password: p
    dbname: test
    sslmode: disable
  influxdb:
    url: localhost
    token: TK
    bucket: jarb
    organization: org