
name: Build & Deploy api to GKE

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/api

jobs:
  build:
    name: Setup, Build, and Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login using Github Token
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          
      - name: Extract branch
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build
        id: build-image
        run: |-
          docker build \
            -f api/Dockerfile \
            --tag "$IMAGE_NAME:$BRANCH" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "$IMAGE_NAME:$BRANCH"

      # Checkout GitOps
      - name: Trigger service deployment in GitOps repo
        run: |-
          curl \
          -u bombnp:${{ secrets.GH_PAT }}
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/bombnp/cloud-final-gitops/dispatches \
          -d '{"event_type":"deploy-service","client_payload":{"namespace":"master","service":"api"}}'
